<?php

class ColumnsStrings
{
    const SCALE_NUMBER = 'Номер';
    const SCALE_TYPE_TEXT = 'Тип';
    const SCALE_CLASS_STATIC = 'Статика';
    const SCALE_CLASS_DYNAMIC = 'Динамика';
    const SCALE_NAME = 'Название';
    const SCALE_MIN_CAPACITY = 'НмПВ';
    const SCALE_MAX_CAPACITY = 'НПВ';
    const SCALE_DISCRETENESS = 'Дискретность';

    const TRAIN_NUM = 'Системный номер поезда';
    const SCALE_NUM = '№ весов';
    const UNIX_TIME = 'Системное время взвешивания';
    const DATETIME = 'Дата и время';
    const DATETIME_END = 'Окончание взвешивания';
    const TRAIN_NUMBER = 'Номер поезда';
    const CARRYING = 'Грузо&shy;подъёмность';
    const LOAD_NORM = 'Норма загрузки';
    const VOLUME = 'Объём';
    const TARE = 'Тара';
    const TARE_WMR = 'Тара ДО';
    const BRUTTO = 'Брутто';
    const NETTO = 'Нетто';
    const OVERLOAD = 'Перегруз';
    const VAN_COUNT = 'Число вагонов';
    const VELOCITY = 'Скорость';
    const OPERATOR = 'Оператор';
    const OPERATOR_TAB_NUMBER = 'Табельный номер';
    const OPERATOR_SHIFT_NUMBER = '№ смены';
    const OPERATOR_SHIFT_SYMBOL = 'Литер смены';
    const DATETIME_OPERATOR = 'Время начала смены';
    const RAIL_PATH = 'Рельсовый путь';
    const STATUS = 'Статус';
    const SEQUENCE_NUMBER = '№ пп';
    const VAN_NUMBER = '№ вагона';
    const VAN_TYPE = 'Род вагона';
    const TARE_MANUAL = 'Тара по трафарету';
    const TARE_DYNAMIC = 'Тара динамическая';
    const TARE_STATIC = 'Тара статическая';
    const TARE_TYPE = 'Используемая тара';
    const TARE_SCALE_NUMBER = '№ весов, взвесивших тару';
    const DATETIME_TARE = 'Дата взвешивания тары';
    const BRUTTO_NEAR_SIDE = 'Брутто на ближний борт';
    const BRUTTO_FAR_SIDE = 'Брутто на дальний борт';
    const BRUTTO_FIRST_CARRIAGE = 'Брутто на первую тележку';
    const BRUTTO_SECOND_CARRIAGE = 'Брутто на вторую тележку';
    const SIDE_DIFFERENCE = 'Разница между бортами';
    const CARRIAGE_DIFFERENCE = 'Разница между тележками';
    const MASS = 'Служебная масса';
    const ACCELERATION = 'Ускорение';
    const CARGO_TYPE = 'Род груза';
    const CARGO_TYPE_CODE = 'Код рода груза';
    const DATETIME_CARGO = 'Дата и время изменения рода груза';
    const AXIS_COUNT = 'Число осей';
    const COUNTRY = 'Принадлежность';
    const DEPART_STATION = 'Станция отправления';
    const DEPART_STATION_CODE = 'Код станции отправления';
    const PURPOSE_STATION = 'Станция назначения';
    const PURPOSE_STATION_CODE = 'Код станции назначения';
    const DATETIME_SHIPMENT = 'Дата отправки';
    const INVOICE_NUMBER = '№ накладной';
    const INVOICE_NUMBER_WMR = '№ выпуска';
    const INVOICE_SUPPLIER = 'Грузо&shy;отправитель';
    const INVOICE_SUPPLIER_WMR = '№ печи';
    const INVOICE_RECIPIENT = 'Грузо&shy;получатель';
    const INVOICE_NETTO = 'Нетто по накладной';
    const INVOICE_NETTO_WMR = 'Чистый вес';
    const INVOICE_TARE = 'Тара по накладной';
    const INVOICE_TARE_WMR = 'Тара ПОСЛЕ';
    const INVOICE_OVERLOAD = 'Перегруз по накладной';
    const INVOICE_OVERLOAD_WMR = 'Потери';
    const LOADING_GROUP = 'Номер группы вагонов';
    const LOADING_PLACE = 'Место погрузки';
    const TARE_NEAR_SIDE = 'Тара на ближний борт';
    const TARE_FAR_SIDE = 'Тара на дальний борт';
    const TARE_FIRST_CARRIAGE = 'Тара на первую тележку';
    const TARE_SECOND_CARRIAGE = 'Тара на вторую тележку';
    const DATETIME_FAILURE = 'Дата появления сбоя';
    const SCALE_CLASS = 'Режим взвешивания';
    const MESSAGE = 'Сообщение';
    const UNIX_TIME_END = 'Системное время окончания калибровки (поверки';
    const UNIT_NUMBER = '№ грузоприемного устройства';
    const DATETIME_T = 'Следующая калибровка (поверка';
    const OPERATION_TYPE = 'Тип операции';
    const ACCURACY_CLASS = 'Класс точности';
    const DISCRETENESS = 'Дискретность';
    const COEFFICIENT_P1 = 'P &gt;&gt;&gt;'; // >>>
    const COEFFICIENT_Q1 = 'Q &gt;&gt;&gt;';
    const COEFFICIENT_T1 = 'T &gt;&gt;&gt;';
    const COEFFICIENT_P2 = 'P &lt;&lt;&lt;'; // <<<
    const COEFFICIENT_Q2 = 'Q &lt;&lt;&lt;';
    const COEFFICIENT_T2 = 'T &lt;&lt;&lt;';
    const TEMPERATURE_1 = 'Темп. 1';
    const TEMPERATURE_2 = 'Темп. 2';
    const TEMPERATURE_3 = 'Темп. 3';
    const TEMPERATURE_4 = 'Темп. 4';
    const TEMPERATURE_5 = 'Темп. 5';
    const TEMPERATURE_6 = 'Темп. 6';
    const TEMPERATURE_7 = 'Темп. 7';
    const TEMPERATURE_8 = 'Темп. 8';
    const VERIFIER = 'Поверитель';
    const COMMENT = 'Комментарий';

    const AUTO_NUMBER = '№ авто';
    const DRIVER = 'Водитель';

    const WEIGH_NAME = 'Весы';
    const PRODUCT = 'Продукт';
    const LEFT_SIDE = 'Сторона';
    const COUNT_ID = 'Количество подач';

    const COMPARE = 'Разница';

    const COMPARE_ALL_SCALES = 'Список вагонов по всем весам';
    const COMPARE_COMPARE_VALUES = 'Сравнение значений';
    const COMPARE_SCALE_NUM = 'Весы №%d';
    const COMPARE_OTHER_SCALES = 'Остальные весы';
    const COMPARE_NUM = '№';

    const MI_DELTA_ABS_BRUTTO = 'Δб';
    const MI_DELTA_ABS_BRUTTO_E = 'Δб!';
    const MI_DELTA_ABS_TARE = 'Δт';
    const MI_DELTA_ABS_TARE_E = 'Δт!';
    const MI_DELTA = 'ПДП';
    const MI_DELTA_E = 'ПДП!';
    const MI_TARE_DYN = 'Тара дин.';
    const MI_TARE_DYN_SCALES = '№ весов, взвесивших тару дин.';
    const MI_TARE_DYN_BDATETIME = 'Дата провески тары дин.';
    const MI_DELTA_ABS_TARE_DYN = 'Δтд';
    const MI_DELTA_ABS_TARE_DYN_E = 'Δтд!';
    const MI_DELTA_DYN = 'ПДП для тары дин.';
    const MI_DELTA_DYN_E = 'ПДП для тары дин.!';
    const MI_TARE_STA = 'Тара стат.';
    const MI_TARE_STA_SCALES = '№ весов, взвесивших тару стат.';
    const MI_TARE_STA_BDATETIME = 'Дата провески тары стат.';
    const MI_DELTA_ABS_TARE_STA = 'Δтс';
    const MI_DELTA_ABS_TARE_STA_E = 'Δтс!';
    const MI_DELTA_STA = 'ПДП для тары стат.';
    const MI_DELTA_STA_E = 'ПДП для тары стат.!';

    const MI_3115_LOSS_SUPPLIER = 'Норма убыли';
    const MI_3115_DELTA_SUPPLIER = 'Погрешность на ст. отправления';
    const MI_3115_DELTA_FROM_TABLES = 'Погрешность на ст. назначения';
    const MI_3115_DELTA_FOR_STATIONS = 'Предельное расхождение';
    const MI_3115_DELTA = 'Погрешность в %';
    const MI_3115_TOLERANCE = 'Погрешность в т';
    const MI_3115_RESULT = 'Результат по МИ 3115';

    const DATE = 'Дата';
    const IRON_ESPC_RAZL = 'ЭСПЦ + Разливка';
    const IRON_ESPC = 'ЭСПЦ';
    const IRON_RAZL = 'Разливка';
    const IRON_SHCH = 'СХЧ';

    const IRON_CONTROL_SCALES_STA = 'Статика: № весов';
    const IRON_CONTROL_SCALES_DYN = 'Динамика: № весов';
    const IRON_CONTROL_DATETIME_STA = 'Статика: Дата и время';
    const IRON_CONTROL_DATETIME_DYN = 'Динамика: Дата и время';
    const IRON_CONTROL_NETTO_STA = 'Статика: Нетто';
    const IRON_CONTROL_NETTO_DYN = 'Динамика: Нетто';
    const IRON_CONTROL_DIFF_DYN_CARR = 'Разница: Динамика и ГП';
    const IRON_CONTROL_DIFF_DYN_STA = 'Разница: Динамика и статика';
}